apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-prod
  namespace: istio-system
spec:
  profile: default
  # Logs de acesso no Envoy (útil pra observabilidade)
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      # Evita a app subir antes do sidecar
      holdApplicationUntilProxyStarts: true

  components:
    pilot:
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: istio
                  operator: In
                  values: ["true"]
        tolerations:
        - key: "istio"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        # Alta disponibilidade mínima
        hpaSpec:
          minReplicas: 2
        podDisruptionBudget:
          minAvailable: 1
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: ClusterIP
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: istio
                  operator: In
                  values: ["true"]
        tolerations:
        - key: "istio"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        # Alta disponibilidade mínima
        hpaSpec:
          minReplicas: 2
        podDisruptionBudget:
          minAvailable: 1